version: '3'
services:
  maplestory:
    container_name: beidou-server
    build:
      context: ../../
      dockerfile: ./gms-server/docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      # Web
      - "8686:8686"
      # Login server
      - "8484:8484"
      # Channels.
      - "7575-7577:7575-7577"
    volumes:
      - ../scripts:/opt/server/scripts
      - ../scripts-zh-CN:/opt/server/scripts-zh-CN
      - ../wz:/opt/server/wz
      - ../wz-zh-CN:/opt/server/wz-zh-CN
      - ./application.yml:/opt/server/application.yml

  db:
    container_name: database
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./docker-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
