CREATE TABLE IF NOT EXISTS `fredstorage`
(
    `id`        INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `cid`       INT(10) UNSIGNED NOT NULL,
    `daynotes`  INT(4) UNSIGNED  NOT NULL,
    `TIMESTAMP` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `cid_2` (`cid`),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;