CREATE TABLE IF NOT EXISTS `characters`
(
    `id`                   INT(11)             NOT NULL AUTO_INCREMENT,
    `accountid`            INT(11)             NOT NULL DEFAULT '0',
    `world`                INT(11)             NOT NULL DEFAULT '0',
    `name`                 VARCHAR(13)         NOT NULL DEFAULT '',
    `level`                INT(11)             NOT NULL DEFAULT '1',
    `exp`                  INT(11)             NOT NULL DEFAULT '0',
    `gachaexp`             INT(11)             NOT NULL DEFAULT '0',
    `str`                  INT(11)             NOT NULL DEFAULT '12',
    `dex`                  INT(11)             NOT NULL DEFAULT '5',
    `luk`                  INT(11)             NOT NULL DEFAULT '4',
    `int`                  INT(11)             NOT NULL DEFAULT '4',
    `hp`                   INT(11)             NOT NULL DEFAULT '50',
    `mp`                   INT(11)             NOT NULL DEFAULT '5',
    `maxhp`                INT(11)             NOT NULL DEFAULT '50',
    `maxmp`                INT(11)             NOT NULL DEFAULT '5',
    `meso`                 INT(11)             NOT NULL DEFAULT '0',
    `hpMpUsed`             INT(11) UNSIGNED    NOT NULL DEFAULT '0',
    `job`                  INT(11)             NOT NULL DEFAULT '0',
    `skincolor`            INT(11)             NOT NULL DEFAULT '0',
    `gender`               INT(11)             NOT NULL DEFAULT '0',
    `fame`                 INT(11)             NOT NULL DEFAULT '0',
    `fquest`               INT(11)             NOT NULL DEFAULT '0',
    `hair`                 INT(11)             NOT NULL DEFAULT '0',
    `face`                 INT(11)             NOT NULL DEFAULT '0',
    `ap`                   INT(11)             NOT NULL DEFAULT '0',
    `sp`                   VARCHAR(128)        NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0',
    `map`                  INT(11)             NOT NULL DEFAULT '0',
    `spawnpoint`           INT(11)             NOT NULL DEFAULT '0',
    `gm`                   TINYINT(1)          NOT NULL DEFAULT '0',
    `party`                INT(11)             NOT NULL DEFAULT '0',
    `buddyCapacity`        INT(11)             NOT NULL DEFAULT '25',
    `createdate`           TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `rank`                 INT(10) UNSIGNED    NOT NULL DEFAULT '1',
    `rankMove`             INT(11)             NOT NULL DEFAULT '0',
    `jobRank`              INT(10) UNSIGNED    NOT NULL DEFAULT '1',
    `jobRankMove`          INT(11)             NOT NULL DEFAULT '0',
    `guildid`              INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `guildrank`            INT(10) UNSIGNED    NOT NULL DEFAULT '5',
    `messengerid`          INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `messengerposition`    INT(10) UNSIGNED    NOT NULL DEFAULT '4',
    `mountlevel`           INT(9)              NOT NULL DEFAULT '1',
    `mountexp`             INT(9)              NOT NULL DEFAULT '0',
    `mounttiredness`       INT(9)              NOT NULL DEFAULT '0',
    `omokwins`             INT(11)             NOT NULL DEFAULT '0',
    `omoklosses`           INT(11)             NOT NULL DEFAULT '0',
    `omokties`             INT(11)             NOT NULL DEFAULT '0',
    `matchcardwins`        INT(11)             NOT NULL DEFAULT '0',
    `matchcardlosses`      INT(11)             NOT NULL DEFAULT '0',
    `matchcardties`        INT(11)             NOT NULL DEFAULT '0',
    `MerchantMesos`        INT(11)                      DEFAULT '0',
    `HasMerchant`          TINYINT(1)                   DEFAULT '0',
    `equipslots`           INT(11)             NOT NULL DEFAULT '24',
    `useslots`             INT(11)             NOT NULL DEFAULT '24',
    `setupslots`           INT(11)             NOT NULL DEFAULT '24',
    `etcslots`             INT(11)             NOT NULL DEFAULT '24',
    `familyId`             INT(11)             NOT NULL DEFAULT '-1',
    `monsterbookcover`     INT(11)             NOT NULL DEFAULT '0',
    `allianceRank`         INT(10)             NOT NULL DEFAULT '5',
    `vanquisherStage`      INT(11) UNSIGNED    NOT NULL DEFAULT '0',
    `ariantPoints`         INT(11) UNSIGNED    NOT NULL DEFAULT '0',
    `dojoPoints`           INT(11) UNSIGNED    NOT NULL DEFAULT '0',
    `lastDojoStage`        INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `finishedDojoTutorial` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `vanquisherKills`      INT(11) UNSIGNED    NOT NULL DEFAULT '0',
    `summonValue`          INT(11) UNSIGNED    NOT NULL DEFAULT '0',
    `partnerId`            INT(11)             NOT NULL DEFAULT '0',
    `marriageItemId`       INT(11)             NOT NULL DEFAULT '0',
    `reborns`              INT(5)              NOT NULL DEFAULT '0',
    `PQPoints`             INT(11)             NOT NULL DEFAULT '0',
    `dataString`           VARCHAR(64)         NOT NULL DEFAULT '',
    `lastLogoutTime`       TIMESTAMP           NOT NULL DEFAULT '2015-01-01 05:00:00',
    `lastExpGainTime`      TIMESTAMP           NOT NULL DEFAULT '2015-01-01 05:00:00',
    `partySearch`          TINYINT(1)          NOT NULL DEFAULT '1',
    `jailexpire`           bigint(20)          NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `accountid` (`accountid`),
    KEY `party` (`party`),
    KEY `ranking1` (`level`, `exp`),
    KEY `ranking2` (`gm`, `job`),
    INDEX (id, accountid, world),
    INDEX (id, accountid, name)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  PACK_KEYS = 0
  AUTO_INCREMENT = 1;