CREATE TABLE IF NOT EXISTS `hp_mp_alert`
(
    `id`   INT(11)          NOT NULL AUTO_INCREMENT,
    `c_id` INT(11) UNSIGNED NOT NULL,
    `hp`   TINYINT UNSIGNED NOT NULL DEFAULT 10,
    `mp`   TINYINT UNSIGNED NOT NULL DEFAULT 10,
    PRIMARY KEY (`id`),
    UNIQUE INDEX (`c_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;