SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `command_info`;
CREATE TABLE `command_info`  (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `syntax` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '指令',
  `level` int NOT NULL COMMENT '指令等级0-6',
  `enabled` tinyint(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 1 COMMENT '0不启用 1启用',
  `command_class_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '指令对应后端java类名',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '指令描述',
  `default_level` int NOT NULL COMMENT '默认指令等级0-6（该字段不可被修改）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 175 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;


INSERT INTO command_info VALUES(1,'help',0,1,'HelpCommand','帮助指令，输出所有可用指令列表',0);
INSERT INTO command_info VALUES(2,'commands',0,1,'HelpCommand','帮助指令，输出所有可用指令列表',0);
INSERT INTO command_info VALUES(3,'droplimit',0,1,'DropLimitCommand','查看服务器最大掉落物数量',0);
INSERT INTO command_info VALUES(4,'time',0,1,'TimeCommand','显示服务器时间',0);
INSERT INTO command_info VALUES(6,'gacha',0,1,'GachaCommand','查询扭蛋机部分奖励列表',0);
INSERT INTO command_info VALUES(7,'dispose',0,1,'DisposeCommand','解卡指令，客户端异常时可以解卡',0);
INSERT INTO command_info VALUES(8,'equiplv',0,1,'EquipLvCommand','显示装备等级',0);
INSERT INTO command_info VALUES(9,'rates',0,1,'ShowRatesCommand','倍率查看',0);
INSERT INTO command_info VALUES(10,'online',0,1,'OnlineCommand','查询在线人数，人物所在位置',0);
INSERT INTO command_info VALUES(11,'bug',0,1,'ReportBugCommand','给GM反馈BUG',0);
INSERT INTO command_info VALUES(12,'points',0,1,'ReadPointsCommand','查询奖励点数和投票点数，暂时没发现有什么用',0);
INSERT INTO command_info VALUES(13,'event',0,1,'JoinEventCommand','参加或离开活动',0);
INSERT INTO command_info VALUES(14,'ranks',0,1,'RanksCommand','查看排名',0);
INSERT INTO command_info VALUES(16,'toggleexp',0,1,'ToggleExpCommand','切换是否获取经验',0);
INSERT INTO command_info VALUES(17,'mapowner',0,1,'MapOwnerClaimCommand','查询地图归属',0);
INSERT INTO command_info VALUES(21,'bosshp',1,1,'BossHpCommand','显示BOSS血量',1);
INSERT INTO command_info VALUES(22,'mobhp',1,1,'MobHpCommand','显示怪物血量',1);
INSERT INTO command_info VALUES(23,'whatdropsfrom',1,1,'WhatDropsFromCommand','查询怪物掉落的物品',1);
INSERT INTO command_info VALUES(24,'whodrops',1,1,'WhoDropsCommand','查询物品掉落的怪物',1);
INSERT INTO command_info VALUES(25,'buffme',1,1,'BuffMeCommand','给自己管理员祝福',1);
INSERT INTO command_info VALUES(26,'goto',1,1,'GotoCommand','移动到指定地图',1);
INSERT INTO command_info VALUES(27,'recharge',2,1,'RechargeCommand','充能您的使用道具。',2);
INSERT INTO command_info VALUES(28,'whereami',2,1,'WhereaMiCommand','查询当前地图中的玩家及NPC',2);
INSERT INTO command_info VALUES(29,'hide',2,1,'HideCommand','隐身',2);
INSERT INTO command_info VALUES(30,'unhide',2,1,'UnHideCommand','解除隐身',2);
INSERT INTO command_info VALUES(31,'sp',2,1,'SpCommand','增加技能点',2);
INSERT INTO command_info VALUES(32,'ap',2,1,'ApCommand','增加能力点数',2);
INSERT INTO command_info VALUES(33,'empowerme',2,1,'EmpowerMeCommand','使用更多的buff强化自己',2);
INSERT INTO command_info VALUES(34,'buffmap',2,1,'BuffMapCommand','地图所有玩家获得Buff',2);
INSERT INTO command_info VALUES(35,'buff',2,1,'BuffCommand','给自己使用BUFF技能',2);
INSERT INTO command_info VALUES(36,'bomb',2,1,'BombCommand','使用炸弹攻击玩家',2);
INSERT INTO command_info VALUES(37,'dc',2,1,'DcCommand','将指定玩家踢下线',2);
INSERT INTO command_info VALUES(38,'cleardrops',2,1,'ClearDropsCommand','清除丢弃的物品',2);
INSERT INTO command_info VALUES(39,'clearslot',2,1,'ClearSlotCommand','清理自己的背包',2);
INSERT INTO command_info VALUES(40,'clearsavelocs',2,1,'ClearSavedLocationsCommand','清除玩家保存的位置',2);
INSERT INTO command_info VALUES(41,'warp',2,1,'WarpCommand','将玩家传送到指定地图。',2);
INSERT INTO command_info VALUES(42,'warphere',2,1,'SummonCommand','将另一个玩家传送到您所在的地图。',2);
INSERT INTO command_info VALUES(43,'warpto',2,1,'ReachCommand','查询玩家在几线',2);
INSERT INTO command_info VALUES(44,'summon',2,1,'SummonCommand','将另一个玩家传送到您所在的地图。',2);
INSERT INTO command_info VALUES(45,'reach',2,1,'ReachCommand','查询玩家在几线',2);
INSERT INTO command_info VALUES(46,'follow',2,1,'ReachCommand','查询玩家在几线',2);
INSERT INTO command_info VALUES(47,'gmshop',2,1,'GmShopCommand','打开GM商店',2);
INSERT INTO command_info VALUES(48,'heal',2,1,'HealCommand','治疗自己',2);
INSERT INTO command_info VALUES(49,'item',2,1,'ItemCommand','添加物品',2);
INSERT INTO command_info VALUES(50,'drop',2,1,'ItemDropCommand','添加掉落',2);
INSERT INTO command_info VALUES(51,'level',2,1,'LevelCommand','设置等级 可降级',2);
INSERT INTO command_info VALUES(52,'levelpro',2,1,'LevelProCommand','提高等级 不可降级',2);
INSERT INTO command_info VALUES(53,'setslot',2,1,'SetSlotCommand','设置玩家的背包槽位数量。',2);
INSERT INTO command_info VALUES(54,'setstat',2,1,'SetStatCommand','设置玩家的属性点数。',2);
INSERT INTO command_info VALUES(55,'maxstat',2,1,'MaxStatCommand','最高等级及属性',2);
INSERT INTO command_info VALUES(56,'maxskill',2,1,'MaxSkillCommand','技能全满',2);
INSERT INTO command_info VALUES(57,'resetskill',2,1,'ResetSkillCommand','重置技能点',2);
INSERT INTO command_info VALUES(58,'search',2,1,'SearchCommand','暂无描述',2);
INSERT INTO command_info VALUES(59,'jail',2,1,'JailCommand','将玩家关进监狱',2);
INSERT INTO command_info VALUES(60,'unjail',2,1,'UnJailCommand','释放监狱玩家',2);
INSERT INTO command_info VALUES(61,'job',2,1,'JobCommand','改变职业',2);
INSERT INTO command_info VALUES(62,'unbug',2,1,'UnBugCommand','解决地图中的卡bug问题。',2);
INSERT INTO command_info VALUES(63,'id',2,1,'IdCommand','查询物品的ID。',2);
INSERT INTO command_info VALUES(64,'gachalist',2,1,'GachaListCommand','查询宝箱物品',2);
INSERT INTO command_info VALUES(65,'loot',2,1,'LootCommand','拾取所有属于你的物品',2);
INSERT INTO command_info VALUES(66,'debuff',3,1,'DebuffCommand','对地图上的玩家施加不同的异常状态。',3);
INSERT INTO command_info VALUES(67,'fly',3,1,'FlyCommand','启用或禁用玩家的飞行功能。',3);
INSERT INTO command_info VALUES(68,'spawn',3,1,'SpawnCommand','生成怪物到玩家当前位置。',3);
INSERT INTO command_info VALUES(69,'mutemap',3,1,'MuteMapCommand','将当前地图静音或取消静音。',3);
INSERT INTO command_info VALUES(70,'checkdmg',3,1,'CheckDmgCommand','检查玩家的最大基础伤害（在技能之前）。',3);
INSERT INTO command_info VALUES(71,'inmap',3,1,'InMapCommand','查看当前地图上的所有玩家。',3);
INSERT INTO command_info VALUES(72,'reloadevents',3,1,'ReloadEventsCommand','重新加载事件脚本',3);
INSERT INTO command_info VALUES(73,'reloaddrops',3,1,'ReloadDropsCommand','重新加载怪物掉落数据。',3);
INSERT INTO command_info VALUES(74,'reloadportals',3,1,'ReloadPortalsCommand','重新加载传送门脚本。',3);
INSERT INTO command_info VALUES(75,'reloadmap',3,1,'ReloadMapCommand','重新加载当前地图。',3);
INSERT INTO command_info VALUES(76,'reloadshops',3,1,'ReloadShopsCommand','重新加载商店脚本。',3);
INSERT INTO command_info VALUES(77,'hpmp',3,1,'HpMpCommand','为指定玩家恢复HP和MP或修改HP和MP值。',3);
INSERT INTO command_info VALUES(78,'maxhpmp',3,1,'MaxHpMpCommand','设置自己或其他玩家的最大HP和MP值。',3);
INSERT INTO command_info VALUES(79,'music',3,1,'MusicCommand','播放指定的游戏音乐。',3);
INSERT INTO command_info VALUES(80,'monitor',3,1,'MonitorCommand','监视或停止监视玩家的活动。',3);
INSERT INTO command_info VALUES(81,'monitors',3,1,'MonitorsCommand','列出当前正在被监视的玩家。',3);
INSERT INTO command_info VALUES(82,'ignore',3,1,'IgnoreCommand','在游戏中忽略或取消忽略指定的玩家。',3);
INSERT INTO command_info VALUES(83,'ignored',3,1,'IgnoredCommand','暂无描述',3);
INSERT INTO command_info VALUES(84,'pos',3,1,'PosCommand','获取玩家当前位置信息和Foothold ID。',3);
INSERT INTO command_info VALUES(85,'togglecoupon',3,1,'ToggleCouponCommand','在服务器上切换优惠券（Coupon）的状态。',3);
INSERT INTO command_info VALUES(86,'togglewhitechat',3,1,'ChatCommand','切换聊天模式。',3);
INSERT INTO command_info VALUES(87,'fame',3,1,'FameCommand','更改玩家的声望（Fame）值。',3);
INSERT INTO command_info VALUES(88,'givenx',3,1,'GiveNxCommand','添加点券',3);
INSERT INTO command_info VALUES(89,'givevp',3,1,'GiveVpCommand','向玩家授予投票点（Vote Points）。',3);
INSERT INTO command_info VALUES(90,'givems',3,1,'GiveMesosCommand','添加金币',3);
INSERT INTO command_info VALUES(91,'giverp',3,1,'GiveRpCommand','向玩家授予奖励点（Reward Points）。',3);
INSERT INTO command_info VALUES(92,'expeds',3,1,'ExpedsCommand','列出服务器中各频道的远征队伍信息。',3);
INSERT INTO command_info VALUES(93,'kill',3,1,'KillCommand','杀死玩家',3);
INSERT INTO command_info VALUES(94,'seed',3,1,'SeedCommand','在HPQ地图中生成种子物品。',3);
INSERT INTO command_info VALUES(95,'maxenergy',3,1,'MaxEnergyCommand','最大道馆能量',3);
INSERT INTO command_info VALUES(96,'killall',3,1,'KillAllCommand','清怪掉落',3);
INSERT INTO command_info VALUES(97,'notice',3,1,'NoticeCommand','发送服务器公告。',3);
INSERT INTO command_info VALUES(98,'rip',3,1,'RipCommand','发送RIP消息。',3);
INSERT INTO command_info VALUES(99,'openportal',3,1,'OpenPortalCommand','打开指定传送门。',3);
INSERT INTO command_info VALUES(100,'closeportal',3,1,'ClosePortalCommand','关闭指定地图上的传送门。',3);
INSERT INTO command_info VALUES(101,'pe',3,1,'PeCommand','模拟接收特定封包以进行调试。',3);
INSERT INTO command_info VALUES(102,'startevent',3,1,'StartEventCommand','在当前地图启动一个事件，可以设置参与玩家数量。',3);
INSERT INTO command_info VALUES(103,'endevent',3,1,'EndEventCommand','结束服务器上正在进行的事件。',3);
INSERT INTO command_info VALUES(104,'startmapevent',3,1,'StartMapEventCommand','在当前地图启动一个事件。',3);
INSERT INTO command_info VALUES(105,'stopmapevent',3,1,'StopMapEventCommand','停止当前地图上正在进行的事件。',3);
INSERT INTO command_info VALUES(106,'online2',3,1,'OnlineTwoCommand','暂无描述',3);
INSERT INTO command_info VALUES(107,'ban',3,1,'BanCommand','禁止玩家访问服务器并记录原因。',3);
INSERT INTO command_info VALUES(108,'unban',3,1,'UnBanCommand','解除封禁某个玩家。',3);
INSERT INTO command_info VALUES(109,'healmap',3,1,'HealMapCommand','恢复当前地图上所有角色的健康（HP和MP）。',3);
INSERT INTO command_info VALUES(110,'healperson',3,1,'HealPersonCommand','为指定玩家恢复健康（HP和MP）。',3);
INSERT INTO command_info VALUES(111,'hurt',3,1,'HurtCommand','伤害指定玩家的1点HP。',3);
INSERT INTO command_info VALUES(112,'killmap',3,1,'KillMapCommand','杀死当前地图上的所有玩家。',3);
INSERT INTO command_info VALUES(113,'night',3,1,'NightCommand','在当前地图上触发夜晚效果。',3);
INSERT INTO command_info VALUES(114,'npc',3,1,'NpcCommand','生成NPC并放置在玩家位置。',3);
INSERT INTO command_info VALUES(115,'face',3,1,'FaceCommand','更改玩家的面部表情（Face）ID。',3);
INSERT INTO command_info VALUES(116,'hair',3,1,'HairCommand','更改玩家的发型。',3);
INSERT INTO command_info VALUES(117,'startquest',3,1,'QuestStartCommand','启动指定任务。',3);
INSERT INTO command_info VALUES(118,'completequest',3,1,'QuestCompleteCommand','强制完成指定任务。',3);
INSERT INTO command_info VALUES(119,'resetquest',3,1,'QuestResetCommand','重置指定任务的进度。',3);
INSERT INTO command_info VALUES(120,'timer',3,1,'TimerCommand','为指定玩家设置计时器或删除计时器。',3);
INSERT INTO command_info VALUES(121,'timermap',3,1,'TimerMapCommand','在游戏地图中为所有玩家设置计时器或删除计时器。',3);
INSERT INTO command_info VALUES(122,'timerall',3,1,'TimerAllCommand','为所有玩家设置计时器或删除计时器。',3);
INSERT INTO command_info VALUES(123,'warpmap',3,1,'WarpMapCommand','将当前地图中的所有玩家传送到指定地图。',2);
INSERT INTO command_info VALUES(124,'warparea',3,1,'WarpAreaCommand','将附近的玩家传送到指定地图。',2);
INSERT INTO command_info VALUES(127,'servermessage',4,1,'ServerMessageCommand','设置服务器的公告信息。',4);
INSERT INTO command_info VALUES(128,'proitem',4,1,'ProItemCommand','为自己创建一个具有指定属性的装备。',4);
INSERT INTO command_info VALUES(129,'seteqstat',4,1,'SetEqStatCommand','为玩家的所有装备设置统一的属性值（如力量、敏捷、生命等）和速度跳跃属性值。',4);
INSERT INTO command_info VALUES(130,'exprate',4,1,'ExpRateCommand','更改游戏服务器的经验倍率。',4);
INSERT INTO command_info VALUES(131,'mesorate',4,1,'MesoRateCommand','更改服务器的金币倍率。',4);
INSERT INTO command_info VALUES(132,'droprate',4,1,'DropRateCommand','更改游戏服务器的掉落率。',4);
INSERT INTO command_info VALUES(133,'bossdroprate',4,1,'BossDropRateCommand','设置服务器的Boss掉落率。',4);
INSERT INTO command_info VALUES(134,'questrate',4,1,'QuestRateCommand','更改服务器的任务倍率。',4);
INSERT INTO command_info VALUES(135,'travelrate',4,1,'TravelRateCommand','设置旅行速度倍率。',4);
INSERT INTO command_info VALUES(136,'fishrate',4,1,'FishingRateCommand','更改游戏服务器的钓鱼概率倍率。',4);
INSERT INTO command_info VALUES(137,'itemvac',4,1,'ItemVacCommand','吸取玩家周围的所有物品。',4);
INSERT INTO command_info VALUES(138,'forcevac',4,1,'ForceVacCommand','强制吸取地图上的所有物品。',4);
INSERT INTO command_info VALUES(139,'zakum',4,1,'ZakumCommand','召唤扎昆怪物。',4);
INSERT INTO command_info VALUES(140,'horntail',4,1,'HorntailCommand','在玩家当前位置生成暗黑龙王。',4);
INSERT INTO command_info VALUES(141,'pinkbean',4,1,'PinkbeanCommand','在玩家位置下方生成Pinkbean BOSS怪物。',4);
INSERT INTO command_info VALUES(142,'pap',4,1,'PapCommand','在玩家位置下方生成Papulatus BOSS怪物。',4);
INSERT INTO command_info VALUES(143,'pianus',4,1,'PianusCommand','在玩家位置下方生成Pianus BOSS怪物。',4);
INSERT INTO command_info VALUES(144,'cake',4,1,'CakeCommand','在游戏地图中生成一个蛋糕怪物。',4);
INSERT INTO command_info VALUES(145,'playernpc',4,1,'PlayerNpcCommand','在当前地图生成一个玩家NPC。',4);
INSERT INTO command_info VALUES(146,'playernpcremove',4,1,'PlayerNpcRemoveCommand','从当前地图移除一个玩家NPC。',4);
INSERT INTO command_info VALUES(147,'pnpc',4,1,'PnpcCommand','在当前地图创建npc',4);
INSERT INTO command_info VALUES(148,'pnpcremove',4,1,'PnpcRemoveCommand','移除当前地图创建的NPC',4);
INSERT INTO command_info VALUES(149,'pmob',4,1,'PmobCommand','在当前地图创建怪物',4);
INSERT INTO command_info VALUES(150,'pmobremove',4,1,'PmobRemoveCommand','移除当前地图创建的怪物',4);
INSERT INTO command_info VALUES(151,'debug',5,1,'DebugCommand','暂无描述',5);
INSERT INTO command_info VALUES(152,'set',5,1,'SetCommand','暂无描述',5);
INSERT INTO command_info VALUES(153,'showpackets',5,1,'ShowPacketsCommand','开启/关闭封包信息',5);
INSERT INTO command_info VALUES(154,'showmovelife',5,1,'ShowMoveLifeCommand','开启/关闭生物移动信息',5);
INSERT INTO command_info VALUES(155,'showsessions',5,1,'ShowSessionsCommand','暂无描述',5);
INSERT INTO command_info VALUES(156,'iplist',5,1,'IpListCommand','暂无描述',5);
INSERT INTO command_info VALUES(157,'setgmlevel',6,1,'SetGmLevelCommand','设置GM等级',6);
INSERT INTO command_info VALUES(158,'warpworld',6,1,'WarpWorldCommand','迁移大区 ',6);
INSERT INTO command_info VALUES(159,'saveall',6,1,'SaveAllCommand','保存',6);
INSERT INTO command_info VALUES(160,'dcall',6,1,'DCAllCommand','将所有玩家踢下线',6);
INSERT INTO command_info VALUES(161,'mapplayers',6,1,'MapPlayersCommand','显示地图中的玩家',6);
INSERT INTO command_info VALUES(162,'getacc',6,1,'GetAccCommand','获取玩家账号',6);
INSERT INTO command_info VALUES(163,'shutdown',6,1,'ShutdownCommand','关闭服务器',6);
INSERT INTO command_info VALUES(164,'clearquestcache',6,1,'ClearQuestCacheCommand','清除任务缓存',6);
INSERT INTO command_info VALUES(165,'clearquest',6,1,'ClearQuestCommand','清除单个任务缓存',6);
INSERT INTO command_info VALUES(166,'supplyratecoupon',6,1,'SupplyRateCouponCommand','允许/禁止现金商店出售利率券',6);
INSERT INTO command_info VALUES(167,'spawnallpnpcs',6,1,'SpawnAllPNpcsCommand','暂无描述',6);
INSERT INTO command_info VALUES(168,'eraseallpnpcs',6,1,'EraseAllPNpcsCommand','清除所有的NPC',6);
INSERT INTO command_info VALUES(169,'addchannel',6,1,'ServerAddChannelCommand','添加频道',6);
INSERT INTO command_info VALUES(170,'addworld',6,1,'ServerAddWorldCommand','创建大区',6);
INSERT INTO command_info VALUES(171,'removechannel',6,1,'ServerRemoveChannelCommand','移除大区的最后一个频道',6);
INSERT INTO command_info VALUES(172,'removeworld',6,1,'ServerRemoveWorldCommand','移除大区',6);