/*
 *  Standalone Area Boss Script Template
 *  
 *  Features:
 *  1. Auto-spawn specific Boss.
 *  2. Listen for death events.
 *  3. Accurate respawn timer reset on death.
 *  4. [New] Lazy Spawn: Only spawns when player enters and cooldown is ready.
 *
 *  Usage:
 *  - Auto-generated by script
 */

// ============================================================================
//                              Configuration
// ============================================================================

// Map ID
const MapID = 677000005;

// Boss ID
const BossID = 9400609;

// Boss Name (Default, updates if DB read)
var BossName = "Area Boss";

// Cooldown (Minutes)
const BossTime = 180;

// Spawn Point (X, Y)
const SpawnPoint = new java.awt.Point(201, 80);

// Boss Announcement
const BossNotice = "Andras has appeared!";

// ============================================================================
//                            Core Logic
// ============================================================================

const LifeFactory = Java.type('org.gms.server.life.LifeFactory');
const PacketCreator = Java.type('org.gms.util.PacketCreator');
const LoggerFactory = Java.type('org.slf4j.LoggerFactory');

var log = null;
var channel = null;

// Event Name (Auto-detected, do not modify)
const EventName = "AreaBossDoor2";

function init() {
    channel = em.getChannelServer().getId();
    log = LoggerFactory.getLogger(em.getName());
    scheduleNew();
}

function scheduleNew() {
    setupEventInstance();

    var eim = getOrCreateEventInstance();
    // Mark: Cooldown ready (Server restart defaults to ready)
    eim.setProperty("canSpawn", "true");

    // Fix: Event must be started for monsterKilled hooks to work
    try { eim.startEvent(); } catch (e) { }

    // Attempt Spawn
    // If map is occupied, spawn immediately
    // If empty, do nothing, wait for player entry
    checkAndSpawn(eim);
}

function cancelSchedule() {
    var eim = em.getInstance(EventName);
    if (eim != null) {
        eim.dispose();
    }
}

// Helper: Get or Create Instance
function getOrCreateEventInstance() {
    var eim = em.getInstance(EventName);
    if (eim == null) {
        try {
            eim = em.newInstance(EventName);
        } catch (e) {
            eim = em.getInstance(EventName);
        }
    }
    return eim;
}

function setupEventInstance() {
    var eim = getOrCreateEventInstance();
    var map = em.getChannelServer().getMapFactory().getMap(MapID);
    // Bind map to EIM
    map.setEventInstance(eim);
}

// Core Monitor Function: Replaces playerEntry polling
function checkAndSpawn(eim) {
    if (eim == null) return;
    
    var canSpawn = eim.getProperty("canSpawn");
    // If not spawnable (already spawned or cooling down), stop checking
    if (canSpawn != "true") {
        return;
    }

    var map = em.getChannelServer().getMapFactory().getMap(MapID);

    // 1. Check Player Count
    if (map.getCharacters().size() > 0) {
        // Map has players, attempt spawn
        spawnBoss(eim, map);
    }
}


function spawnBoss(eim, map) {
    try {
        // Double Check: Ensure Boss doesn't already exist
        if (map.getMonsterById(BossID) != null) {
            eim.setProperty("canSpawn", "false");
            return;
        }

        // Prepare Boss Object
        var bossMob = LifeFactory.getMonster(BossID);
        if (bossMob.getName()) {
            BossName = bossMob.getName();
        }

        // Spawn Boss
        map.spawnMonsterOnGroundBelow(bossMob, SpawnPoint);

        // Mark as non-spawnable
        eim.setProperty("canSpawn", "false");

        if (log) log.info(`[Field Boss] ${EventName} spawned ${BossName}(${BossID}) on channel ${channel}`);

        // Send Broadcast
        map.broadcastMessage(PacketCreator.serverNotice(6, `[Field Boss] ${BossName}  ${BossNotice}`));

    } catch (e) {
        if (log) log.error(`[Field Boss] ${EventName} failed to spawn`, e);
    }
}

// ============================================================================
//                            Event Hooks
// ============================================================================

// Triggered when player enters map (Field Boss specific hook)
function onMapUserEnter(eim, player) {
    if (log) log.info(`[Field Boss] ${EventName} player entry check`);
    checkAndSpawn(eim);
}

function monsterKilled(mob, eim) {
    // Check if the killed monster is the target Boss
    if (mob.getId() == BossID) {
        var nextRespawnTime = em.getBossTime(BossTime * 60 * 1000);

        if (log) log.info(`[Field Boss] ${BossName}(${BossID}) killed, respawning in ${nextRespawnTime / 60000} mins`);

        // Set cooldown timer
        em.schedule("cooldownFinished", nextRespawnTime);
    }
}

// Timer Callback: Cooldown Finished
function cooldownFinished() {
    var eim = getOrCreateEventInstance();
    // Mark cooldown finished
    eim.setProperty("canSpawn", "true");

    // Start monitoring
    if (log) log.info(`[Field Boss] ${EventName} cooldown finished, waiting for player`);
    checkAndSpawn(eim);
}

// Required Empty Functions
function playerEntry(eim, player) { }
function dispose() { }
function setup(eim, leaderid) { }
function monsterValue(eim, mobid) { return 0; }
function disbandParty(eim, player) { }
function playerDisconnected(eim, player) { }
function scheduledTimeout(eim) { }
function afterSetup(eim) { }
function changedLeader(eim, leader) { }
function playerExit(eim, player) { }
function leftParty(eim, player) { }
function clearPQ(eim) { }
function allMonstersDead(eim) { }
function playerUnregistered(eim, player) { }
function playerRevive(eim, player) { return true; }